branches:
  except:
    - /travis/
    - /github-actions/
    - /doozer/
skip_tags: true

#cache:
#  - C:\strawberry

environment:
  matrix:
## ppm downloads do not work anymore, since beginning of June 2024
#    - perl: activeperl
#      make: dmake
    - perl: strawberryperl
      make: gmake

install:
  - if %perl%==strawberryperl ( if not exist "C:\strawberry" cinst strawberryperl )
  - if %perl%==strawberryperl   set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - if %perl%==activeperl       ppm install dmake YAML-LibYAML
  - if %perl%==strawberryperl ( cpanm --installdeps . && cpanm --notest YAML::XS )

build_script:
  - perl Makefile.PL
  - '%make% test'
